services:
# shuba_blog.example:
# class: Shuba\BlogBundle\Example
# arguments: [@service_id, "plain_value", %parameter%]
    shuba_blog.example:
         class: Shuba\BlogBundle\Twig\GuestbookExtension
         tags:
            - { name: twig.extension }
    shuba_repository:
         class: Shuba\BlogBundle\Entity\MessageRepository
         factory-service: doctrine.orm.entity_manager
         factory-method: getRepository
         arguments: [ShubaBlogBundle:Message]
    shuba_search:
         class: Shuba\BlogBundle\Service\SearchService\Search
         arguments: [@shuba_repository]
