services:
#    shuba_blog.example:
#        class: Shuba\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    shuba_blog.example:
        class: Shuba\BlogBundle\Twig\GuestbookExtension
        tags:
            - { name: twig.extension }
    shuba_blog.search:
        class: Shuba\BlogBundle\Service\SearchService\Search
        tags:
            - { name: search }