<?php

namespace Shuba\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findLatestPostsLimit($last_posts_limit)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM ShubaBlogBundle:Post p ORDER BY p.id DESC')
            ->setMaxResults($last_posts_limit)
            ->getResult();
    }

    public function findMostViewedtPosts($limit)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM ShubaBlogBundle:Post p ORDER BY p.viewsNumber DESC')
            ->setMaxResults($limit)
            ->getResult();
    }
}
